# Generated by Django 3.2.1 on 2021-05-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FreeFlowClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(max_length=50, verbose_name='telephone')),
                ('country', models.CharField(max_length=50, verbose_name='country')),
                ('message', models.CharField(max_length=200, verbose_name='message')),
                ('privatePerson', models.BooleanField(default=True, verbose_name='is private person')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
            ],
        ),
        migrations.CreateModel(
            name='FreeFlowStores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('img', models.ImageField(upload_to='')),
                ('url', models.URLField()),
            ],
        ),
    ]
