# Generated by Django 3.2.1 on 2021-05-05 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freeFlow', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FreeFlowClient',
        ),
    ]
